apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2017-06-15T14:42:49Z
    labels:
      io.kompose.service: boilerplate
    name: boilerplate
    namespace: default
    resourceVersion: "1561"
    selfLink: /api/v1/namespaces/default/services/boilerplate
    uid: e792e4b3-51d8-11e7-8167-42010a800254
  spec:
    ports:
    - name: "3000"
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      io.kompose.service: boilerplate
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""